import React, { useState, useEffect, useRef } from "react";
import { ShieldCheck, ArrowRight, Clock, KeyRound, AlertCircle, RefreshCw } from "lucide-react";
import { apiClient } from "@/utils/apiClient";

interface OtpVerificationModalProps {
  isOpen: boolean;
  stepUpToken: string;
  onSuccess: (data: any) => void;
  onCancel: () => void;
}

export const OtpVerificationModal: React.FC<OtpVerificationModalProps> = ({
  isOpen,
  stepUpToken,
  onSuccess,
  onCancel
}) => {
  const [digits, setDigits] = useState<string[]>(["", "", "", "", "", ""]);
  const [useBackupCode, setUseBackupCode] = useState(false);
  const [backupCodeInput, setBackupCodeInput] = useState("");
  const [rememberDevice, setRememberDevice] = useState(true);
  const [trustDays, setTrustDays] = useState(15);

  const [timeLeft, setTimeLeft] = useState(30);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const inputRefs = useRef<(HTMLInputElement | null)[]>([]);

  // Countdown timer for 30s TOTP window
  useEffect(() => {
    if (!isOpen) return;
    const calcSeconds = () => 30 - (Math.floor(Date.now() / 1000) % 30);
    setTimeLeft(calcSeconds());

    const interval = setInterval(() => {
      const remaining = calcSeconds();
      setTimeLeft(remaining);
    }, 1000);

    return () => clearInterval(interval);
  }, [isOpen]);

  // Auto-focus first box on open
  useEffect(() => {
    if (isOpen && !useBackupCode) {
      setTimeout(() => inputRefs.current[0]?.focus(), 100);
    }
  }, [isOpen, useBackupCode]);

  if (!isOpen) return null;

  const handleDigitChange = (index: number, val: string) => {
    const cleanVal = val.replace(/\D/g, "");
    if (!cleanVal && val !== "") return;

    const newDigits = [...digits];
    newDigits[index] = cleanVal.slice(-1);
    setDigits(newDigits);
    setError(null);

    // Auto advance
    if (cleanVal && index < 5) {
      inputRefs.current[index + 1]?.focus();
    }
  };

  const handleKeyDown = (index: number, e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Backspace" && !digits[index] && index > 0) {
      inputRefs.current[index - 1]?.focus();
    }
  };

  const handlePaste = (e: React.ClipboardEvent) => {
    e.preventDefault();
    const pasted = e.clipboardData.getData("text").replace(/\D/g, "").slice(0, 6);
    if (pasted.length === 6) {
      setDigits(pasted.split(""));
      setError(null);
      inputRefs.current[5]?.focus();
    }
  };

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setError(null);
    setLoading(true);

    try {
      if (useBackupCode) {
        if (!backupCodeInput.trim()) {
          setError("Please enter a backup recovery code.");
          setLoading(false);
          return;
        }
        const res = await apiClient("/mfa/backup-codes/verify", {
          method: "POST",
          body: JSON.stringify({ code: backupCodeInput.trim(), stepUpToken })
        });
        onSuccess(res);
      } else {
        const otpCode = digits.join("");
        if (otpCode.length < 6) {
          setError("Please enter all 6 digits.");
          setLoading(false);
          return;
        }
        const res = await apiClient("/mfa/verify", {
          method: "POST",
          body: JSON.stringify({
            code: otpCode,
            stepUpToken,
            rememberDevice,
            trustDays
          })
        });
        onSuccess(res);
      }
    } catch (err: any) {
      setError(err.message || "Verification failed. Invalid code.");
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="fixed inset-0 z-[100] flex items-center justify-center bg-black/80 backdrop-blur-xl p-4 animate-fadeIn">
      <div className="bg-card border border-border rounded-3xl w-full max-w-md p-7 shadow-[0_0_80px_rgba(139,92,246,0.3)] text-foreground relative overflow-hidden">
        
        {/* Top Glow Bar */}
        <div className="absolute top-0 left-0 right-0 h-1 bg-gradient-to-r from-violet-500 via-indigo-500 to-emerald-400" />

        <div className="text-center space-y-3 mb-6">
          <div className="h-14 w-14 rounded-2xl bg-gradient-to-br from-violet-500/20 to-indigo-500/10 border border-violet-500/30 flex items-center justify-center text-violet-600 dark:text-violet-400 mx-auto shadow-inner">
            <ShieldCheck className="h-7 w-7" />
          </div>
          <h2 className="text-xl font-bold text-foreground tracking-tight">Enter Verification Code</h2>
          <p className="text-xs text-muted-foreground leading-relaxed">
            {useBackupCode 
              ? "Enter one of your 10 single-use recovery backup codes." 
              : "Please enter the 6-digit code generated by Microsoft Authenticator."}
          </p>
        </div>

        {error && (
          <div className="mb-5 p-3.5 rounded-2xl bg-rose-500/10 border border-rose-500/30 text-rose-600 dark:text-rose-350 text-xs flex items-center gap-2.5 shadow-sm">
            <AlertCircle className="h-4 w-4 text-rose-500 shrink-0" />
            <span>{error}</span>
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {!useBackupCode ? (
            <div>
              {/* 6 Digits Auto-Advance Input */}
              <div className="flex justify-center gap-2.5 mb-4" onPaste={handlePaste}>
                {digits.map((d, i) => (
                  <input
                    key={i}
                    ref={(el) => { inputRefs.current[i] = el; }}
                    type="text"
                    inputMode="numeric"
                    maxLength={1}
                    value={d}
                    onChange={(e) => handleDigitChange(i, e.target.value)}
                    onKeyDown={(e) => handleKeyDown(i, e)}
                    className="w-11 h-13 bg-background border border-border rounded-xl text-center text-xl font-bold text-violet-600 dark:text-violet-300 outline-none focus:border-violet-500 focus:ring-4 focus:ring-violet-500/20 transition-all font-mono shadow-inner"
                  />
                ))}
              </div>

              {/* 30s Window Timer indicator */}
              <div className="flex items-center justify-between px-2 text-xs text-muted-foreground">
                <span className="flex items-center gap-1.5 text-[11px]">
                  <Clock className="h-3.5 w-3.5 text-violet-600 dark:text-violet-400 animate-spin-slow" /> Next code in:
                </span>
                <span className="font-mono font-bold text-violet-600 dark:text-violet-300">{timeLeft}s</span>
              </div>
            </div>
          ) : (
            <div className="space-y-2">
              <label className="text-[11px] font-bold text-muted-foreground uppercase tracking-wider">Backup Recovery Code</label>
              <input
                type="text"
                placeholder="e.g. 8FJ4-KD72"
                value={backupCodeInput}
                onChange={(e) => setBackupCodeInput(e.target.value.toUpperCase())}
                className="w-full h-11 bg-background border border-border rounded-xl px-4 text-center font-mono text-base font-bold text-emerald-600 dark:text-emerald-300 uppercase tracking-widest outline-none focus:border-emerald-500 focus:ring-4 focus:ring-emerald-500/20 transition-all"
              />
            </div>
          )}

          {/* Trusted Device Selector */}
          {!useBackupCode && (
            <div className="p-3.5 rounded-2xl bg-muted/40 border border-border space-y-2">
              <label className="flex items-center gap-2.5 text-xs text-foreground cursor-pointer select-none">
                <input
                  type="checkbox"
                  checked={rememberDevice}
                  onChange={(e) => setRememberDevice(e.target.checked)}
                  className="rounded border-border bg-background text-violet-600 focus:ring-violet-500 h-4 w-4"
                />
                <span className="font-medium">Trust & remember this device</span>
              </label>
              {rememberDevice && (
                <div className="flex items-center gap-2 pt-1 pl-6">
                  <span className="text-[10px] text-muted-foreground">Trust duration:</span>
                  {[7, 15, 30].map((days) => (
                    <button
                      key={days}
                      type="button"
                      onClick={() => setTrustDays(days)}
                      className={`px-2 py-0.5 rounded-md text-[10px] font-bold transition-all ${
                        trustDays === days 
                          ? "bg-violet-600/40 text-violet-750 dark:text-violet-200 border border-violet-500/50" 
                          : "bg-muted text-muted-foreground border border-border"
                      }`}
                    >
                      {days} Days
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}

          <button
            type="submit"
            disabled={loading}
            className="w-full h-11 rounded-2xl bg-gradient-to-r from-violet-600 to-indigo-600 hover:from-violet-500 hover:to-indigo-500 text-white text-xs font-bold shadow-lg shadow-violet-600/30 transition-all flex items-center justify-center gap-2 cursor-pointer disabled:opacity-50"
          >
            {loading ? <RefreshCw className="h-4 w-4 animate-spin" /> : <>Verify Code <ArrowRight className="h-4 w-4" /></>}
          </button>
        </form>

        <div className="mt-6 pt-4 border-t border-border flex items-center justify-between text-xs">
          <button
            type="button"
            onClick={() => { setUseBackupCode(!useBackupCode); setError(null); }}
            className="text-violet-600 dark:text-violet-400 hover:text-violet-500 dark:hover:text-violet-300 font-semibold flex items-center gap-1 cursor-pointer bg-transparent border-none"
          >
            <KeyRound className="h-3.5 w-3.5" />
            {useBackupCode ? "Use Authenticator App" : "Use Backup Code"}
          </button>
          <button
            type="button"
            onClick={onCancel}
            className="text-muted-foreground hover:text-foreground transition-colors cursor-pointer bg-transparent border-none"
          >
            Cancel Login
          </button>
        </div>
      </div>
    </div>
  );
};
