package com.devtrack.api.services;

import org.apache.poi.common.usermodel.HyperlinkType;
import org.apache.poi.ss.usermodel.*;
import org.apache.poi.ss.util.CellRangeAddress;
import org.apache.poi.xddf.usermodel.chart.*;
import org.apache.poi.xssf.usermodel.*;
import org.springframework.stereotype.Service;

import java.io.ByteArrayOutputStream;
import java.security.MessageDigest;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.*;

/**
 * Pure formatter: turns the enriched JSON payload produced by the frontend CR
 * export into a premium multi-sheet .xlsx workbook. Intentionally has NO
 * repository / entity coupling so it can never throw lazy-loading errors and is
 * trivial to reason about. All data fidelity decisions live in the frontend
 * (which already has tasks + bugs + audit logs loaded).
 */
@Service
public class CrAuditReportService {

    private static final DateTimeFormatter TS = DateTimeFormatter.ofPattern("dd-MMM-yyyy hh:mm a");

    // ── Brand palette (shared with the PDF / analytics exports) ─────────────
    private static XSSFColor c(int r, int g, int b) {
        return new XSSFColor(new byte[]{(byte) r, (byte) g, (byte) b}, null);
    }

    // ────────────────────────────────────────────────────────────────────────
    @SuppressWarnings("unchecked")
    public byte[] generate(Map<String, Object> payload) throws Exception {
        Map<String, Object> meta = asMap(payload.get("meta"));
        Map<String, Object> summary = asMap(payload.get("summary"));
        List<Map<String, Object>> crs = asList(payload.get("crs"));
        List<Map<String, Object>> bugs = asList(payload.get("bugs"));

        try (XSSFWorkbook wb = new XSSFWorkbook()) {
            S s = new S(wb);
            buildSummarySheet(wb, s, meta, summary, crs);
            buildCrSheet(wb, s, meta, crs);
            buildBugSheet(wb, s, bugs);

            ByteArrayOutputStream out = new ByteArrayOutputStream();
            wb.write(out);
            return out.toByteArray();
        }
    }

    // ── Summary sheet ────────────────────────────────────────────────────────
    private void buildSummarySheet(XSSFWorkbook wb, S s, Map<String, Object> meta,
                                   Map<String, Object> summary, List<Map<String, Object>> crs) {
        XSSFSheet sheet = wb.createSheet("Summary");
        sheet.setDisplayGridlines(false);
        sheet.setColumnWidth(0, 6800);
        sheet.setColumnWidth(1, 8200);
        sheet.setColumnWidth(2, 1400);
        sheet.setColumnWidth(3, 1400);
        sheet.setColumnWidth(4, 1400);
        sheet.setColumnWidth(5, 5200);
        sheet.setColumnWidth(6, 2600);

        // Title band
        Row band = sheet.createRow(0);
        band.setHeightInPoints(38);
        cell(band, 0, "DEVTRACK 2.0 \u2014 CHANGE REQUEST AUDIT REPORT", s.title);
        for (int i = 1; i <= 6; i++) cell(band, i, "", s.title);
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, 6));

        String genOn = str(meta, "generatedOn");
        if (genOn.isEmpty()) genOn = LocalDateTime.now().format(TS);

        int r = 2;
        r = kv(sheet, s, r, "Generated On", genOn);
        r = kv(sheet, s, r, "Generated By", orDash(str(meta, "generatedBy")));
        r = kv(sheet, s, r, "Project", orDash(str(meta, "project")));
        r = kv(sheet, s, r, "Sprint", orDash(str(meta, "sprint")));
        r++;

        r = kvBadge(sheet, s, r, "Total CRs", intOf(summary, "totalCRs"), s.info);
        r = kvBadge(sheet, s, r, "Completed", intOf(summary, "completed"), s.good);
        r = kvBadge(sheet, s, r, "In Progress", intOf(summary, "inProgress"), s.warn);
        r = kvBadge(sheet, s, r, "Blocked", intOf(summary, "blocked"), s.bad);
        r = kvBadge(sheet, s, r, "Cancelled", intOf(summary, "cancelled"), s.neutral);
        r++;
        r = kvBadge(sheet, s, r, "Total Bugs Raised", intOf(summary, "totalBugsRaised"), s.warn);
        r = kvBadge(sheet, s, r, "Total Bugs Fixed", intOf(summary, "totalBugsFixed"), s.good);
        r++;
        Double avg = dbl(summary, "averageCycleTimeDays");
        r = kv(sheet, s, r, "Average Cycle Time", avg == null ? "\u2014" : (round1(avg) + " days"));

        // ── Small data table (F/G) that feeds the chart ──
        int tCol = 5, vCol = 6, tStart = 3;
        String[] cats = {"Completed", "In Progress", "Blocked", "Cancelled"};
        int[] vals = {intOf(summary, "completed"), intOf(summary, "inProgress"),
                intOf(summary, "blocked"), intOf(summary, "cancelled")};
        cell(sheet.getRow(tStart - 1) != null ? sheet.getRow(tStart - 1) : sheet.createRow(tStart - 1),
                tCol, "CR Status", s.header);
        cell(sheet.getRow(tStart - 1), vCol, "Count", s.header);
        for (int i = 0; i < cats.length; i++) {
            Row rr = sheet.getRow(tStart + i);
            if (rr == null) rr = sheet.createRow(tStart + i);
            cell(rr, tCol, cats[i], s.body);
            Cell cv = rr.createCell(vCol);
            cv.setCellValue(vals[i]);
            cv.setCellStyle(s.num);
        }

        // ── Chart: CRs by status ──
        try {
            XSSFDrawing drawing = sheet.createDrawingPatriarch();
            XSSFClientAnchor anchor = drawing.createAnchor(0, 0, 0, 0, 0, 20, 5, 38);
            XSSFChart chart = drawing.createChart(anchor);
            chart.setTitleText("CRs by Status");
            chart.setTitleOverlay(false);
            XDDFChartLegend legend = chart.getOrAddLegend();
            legend.setPosition(LegendPosition.BOTTOM);
            XDDFCategoryAxis catAx = chart.createCategoryAxis(AxisPosition.BOTTOM);
            XDDFValueAxis valAx = chart.createValueAxis(AxisPosition.LEFT);
            valAx.setCrosses(AxisCrosses.AUTO_ZERO);
            XDDFDataSource<String> catDs = XDDFDataSourcesFactory.fromStringCellRange(sheet,
                    new CellRangeAddress(tStart, tStart + cats.length - 1, tCol, tCol));
            XDDFNumericalDataSource<Double> valDs = XDDFDataSourcesFactory.fromNumericCellRange(sheet,
                    new CellRangeAddress(tStart, tStart + cats.length - 1, vCol, vCol));
            XDDFBarChartData data = (XDDFBarChartData) chart.createData(ChartTypes.BAR, catAx, valAx);
            data.setBarDirection(BarDirection.COL);
            XDDFBarChartData.Series series = (XDDFBarChartData.Series) data.addSeries(catDs, valDs);
            series.setTitle("CRs", null);
            chart.plot(data);
        } catch (Exception ignore) {
            // Chart is a nice-to-have; never fail the export because of it.
        }

        // ── Footer / auditability block ──
        int fr = Math.max(r + 2, 24);
        String exportId = "EXP-" + LocalDateTime.now().format(DateTimeFormatter.ofPattern("yyyyMMdd"))
                + "-" + String.format("%05d", new Random().nextInt(100000));
        fr = kv(sheet, s, fr, "Report Version", "v2.4");
        fr = kv(sheet, s, fr, "Export ID", exportId);
        fr = kv(sheet, s, fr, "SHA-256 Checksum", checksum(crs));
        Row conf = sheet.createRow(fr);
        conf.setHeightInPoints(20);
        cell(conf, 0, "CONFIDENTIAL \u2014 Internal Use Only", s.footer);
        for (int i = 1; i <= 6; i++) cell(conf, i, "", s.footer);
        sheet.addMergedRegion(new CellRangeAddress(fr, fr, 0, 6));
    }

    private int kv(XSSFSheet sheet, S s, int r, String label, String value) {
        Row row = sheet.createRow(r);
        cell(row, 0, label, s.sumLabel);
        cell(row, 1, value, s.sumValue);
        return r + 1;
    }

    private int kvBadge(XSSFSheet sheet, S s, int r, String label, int value, XSSFCellStyle badge) {
        Row row = sheet.createRow(r);
        cell(row, 0, label, s.sumLabel);
        Cell v = row.createCell(1);
        v.setCellValue(value);
        v.setCellStyle(badge);
        return r + 1;
    }

    // ── CR Audit sheet ────────────────────────────────────────────────────────
    private static final String[] CR_HEADERS = {
            "CR Number", "Title", "Project", "Module", "Sprint", "CR Type", "Priority", "Workflow State", "Prod Readiness",
            "Open Bugs", "Total Bugs", "Linked Bug IDs",
            "Primary Developer", "Secondary Developers", "Tester", "Approver", "Deployment Owner", "Created By",
            "Created", "Dev Start", "SIT Deploy", "SIT Completed", "Code Review", "Testing Completed", "UAT Deploy", "UAT Completed", "Prod Deploy",
            "Development Time (days)", "Testing Time (days)", "Total Cycle Time (days)",
            "Git Branch", "Pull Request", "Merge Date", "Git Links",
            "Quality Risk", "Rollback Count", "Total Retests", "Code Reviewed", "Test Evidence Attached", "Efforts (Days)"
    };

    private void buildCrSheet(XSSFWorkbook wb, S s, Map<String, Object> meta, List<Map<String, Object>> crs) {
        XSSFSheet sheet = wb.createSheet("CR Audit");
        sheet.setDisplayGridlines(false);
        String baseUrl = str(meta, "baseUrl");
        CreationHelper helper = wb.getCreationHelper();

        Row band = sheet.createRow(0);
        band.setHeightInPoints(24);
        cell(band, 0, "Change Request Audit \u2014 detailed register", s.subtitle);
        for (int i = 1; i < CR_HEADERS.length; i++) cell(band, i, "", s.subtitle);
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, CR_HEADERS.length - 1));

        Row hdr = sheet.createRow(1);
        for (int i = 0; i < CR_HEADERS.length; i++) cell(hdr, i, CR_HEADERS[i], s.header);

        int rowIdx = 2;
        for (Map<String, Object> cr : crs) {
            Row row = sheet.createRow(rowIdx);
            boolean zebra = (rowIdx % 2) == 0;
            XSSFCellStyle bs = zebra ? s.bodyZebra : s.body;
            XSSFCellStyle ns = zebra ? s.numZebra : s.num;
            int col = 0;

            // CR Number (clickable to the CR page)
            Cell crCell = row.createCell(col++);
            crCell.setCellValue(str(cr, "crNumber"));
            String crId = str(cr, "id");
            if (!baseUrl.isEmpty() && !crId.isEmpty()) {
                Hyperlink link = helper.createHyperlink(HyperlinkType.URL);
                link.setAddress(baseUrl + "/dashboard/crs?cr=" + crId);
                crCell.setHyperlink(link);
                crCell.setCellStyle(s.link);
            } else {
                crCell.setCellStyle(bs);
            }

            cell(row, col++, str(cr, "title"), bs);
            cell(row, col++, str(cr, "project"), bs);
            cell(row, col++, str(cr, "module"), bs);
            cell(row, col++, str(cr, "sprint"), bs);
            cell(row, col++, str(cr, "crType"), bs);
            cell(row, col++, str(cr, "priority"), priorityStyle(s, str(cr, "priority"), bs));
            cell(row, col++, humanize(str(cr, "status")), bs);
            cell(row, col++, str(cr, "prodReadiness"), readinessStyle(s, str(cr, "prodReadiness"), bs));

            numCell(row, col++, dbl(cr, "openBugs"), ns);
            numCell(row, col++, dbl(cr, "totalBugs"), ns);
            cell(row, col++, str(cr, "linkedBugIds"), bs);

            cell(row, col++, orDash(str(cr, "primaryDeveloper")), bs);
            cell(row, col++, str(cr, "secondaryDevelopers"), bs);
            cell(row, col++, orDash(str(cr, "tester")), bs);
            cell(row, col++, orDash(str(cr, "approver")), bs);
            cell(row, col++, orDash(str(cr, "deploymentOwner")), bs);
            cell(row, col++, orDash(str(cr, "createdBy")), bs);

            cell(row, col++, dateStr(cr, "createdDate"), bs);
            cell(row, col++, dateStr(cr, "devStartDate"), bs);
            cell(row, col++, dateStr(cr, "sitDeployDate"), bs);
            cell(row, col++, dateStr(cr, "sitCompletedDate"), bs);
            cell(row, col++, dateStr(cr, "codeReviewDate"), bs);
            cell(row, col++, dateStr(cr, "testingCompletedDate"), bs);
            cell(row, col++, dateStr(cr, "uatDeployDate"), bs);
            cell(row, col++, dateStr(cr, "uatCompletedDate"), bs);
            cell(row, col++, dateStr(cr, "prodDeployDate"), bs);

            numCell(row, col++, dbl(cr, "developmentTimeDays"), ns);
            numCell(row, col++, dbl(cr, "testingTimeDays"), ns);
            numCell(row, col++, dbl(cr, "totalCycleTimeDays"), ns);

            cell(row, col++, str(cr, "gitBranch"), bs);
            cell(row, col++, str(cr, "prLink"), bs);
            cell(row, col++, dateStr(cr, "mergeDate"), bs);
            cell(row, col++, str(cr, "gitLinks"), bs);

            String qr = bool(cr, "qualityRisk") ? "Yes" : "No";
            cell(row, col++, qr, bool(cr, "qualityRisk") ? s.bad : bs);
            numCell(row, col++, dbl(cr, "rollbackCount"), ns);
            numCell(row, col++, dbl(cr, "totalRetests"), ns);
            cell(row, col++, bool(cr, "codeReviewed") ? "Yes" : "No", bool(cr, "codeReviewed") ? s.good : bs);
            cell(row, col++, bool(cr, "testEvidenceAttached") ? "Yes" : "No", bool(cr, "testEvidenceAttached") ? s.good : bs);
            numCell(row, col++, dbl(cr, "efforts"), ns);

            rowIdx++;
        }

        sheet.createFreezePane(1, 2);
        int lastRow = Math.max(2, rowIdx - 1);
        sheet.setAutoFilter(new CellRangeAddress(1, lastRow, 0, CR_HEADERS.length - 1));
        autosize(sheet, CR_HEADERS.length);
    }

    // ── Bugs sheet ────────────────────────────────────────────────────────────
    private static final String[] BUG_HEADERS = {
            "Bug ID", "CR Number", "Title", "Severity", "Priority", "Status",
            "Raised By", "Assigned Developer", "Raised Date", "Resolved Date"
    };

    private void buildBugSheet(XSSFWorkbook wb, S s, List<Map<String, Object>> bugs) {
        XSSFSheet sheet = wb.createSheet("Bugs");
        sheet.setDisplayGridlines(false);
        CreationHelper helper = wb.getCreationHelper();

        Row band = sheet.createRow(0);
        band.setHeightInPoints(24);
        cell(band, 0, "Linked Bugs \u2014 click a Bug ID to open it in DevTrack", s.subtitle);
        for (int i = 1; i < BUG_HEADERS.length; i++) cell(band, i, "", s.subtitle);
        sheet.addMergedRegion(new CellRangeAddress(0, 0, 0, BUG_HEADERS.length - 1));

        Row hdr = sheet.createRow(1);
        for (int i = 0; i < BUG_HEADERS.length; i++) cell(hdr, i, BUG_HEADERS[i], s.header);

        int rowIdx = 2;
        for (Map<String, Object> b : bugs) {
            Row row = sheet.createRow(rowIdx);
            boolean zebra = (rowIdx % 2) == 0;
            XSSFCellStyle bs = zebra ? s.bodyZebra : s.body;
            int col = 0;

            Cell idCell = row.createCell(col++);
            idCell.setCellValue(str(b, "bugId"));
            String url = str(b, "url");
            if (!url.isEmpty()) {
                Hyperlink link = helper.createHyperlink(HyperlinkType.URL);
                link.setAddress(url);
                idCell.setHyperlink(link);
                idCell.setCellStyle(s.link);
            } else {
                idCell.setCellStyle(bs);
            }

            cell(row, col++, str(b, "crNumber"), bs);
            cell(row, col++, str(b, "title"), bs);
            cell(row, col++, str(b, "severity"), severityStyle(s, str(b, "severity"), bs));
            cell(row, col++, str(b, "priority"), bs);
            cell(row, col++, str(b, "status"), bugStatusStyle(s, str(b, "status"), bs));
            cell(row, col++, orDash(str(b, "raisedBy")), bs);
            cell(row, col++, orDash(str(b, "assignedDeveloper")), bs);
            cell(row, col++, dateStr(b, "raisedDate"), bs);
            cell(row, col++, dateStr(b, "resolvedDate"), bs);
            rowIdx++;
        }

        sheet.createFreezePane(1, 2);
        int lastRow = Math.max(2, rowIdx - 1);
        sheet.setAutoFilter(new CellRangeAddress(1, lastRow, 0, BUG_HEADERS.length - 1));
        autosize(sheet, BUG_HEADERS.length);
    }

    // ── Conditional styling helpers ────────────────────────────────────────────
    private XSSFCellStyle priorityStyle(S s, String p, XSSFCellStyle fallback) {
        if (p == null) return fallback;
        switch (p.trim().toLowerCase()) {
            case "high": return s.bad;
            case "medium": return s.warn;
            case "low": return s.neutral;
            default: return fallback;
        }
    }

    private XSSFCellStyle readinessStyle(S s, String v, XSSFCellStyle fallback) {
        if (v == null) return fallback;
        String x = v.toLowerCase();
        if (x.contains("ready")) return s.good;
        if (x.contains("deployed")) return s.info;
        if (x.contains("block")) return s.bad;
        if (x.contains("cancel")) return s.neutral;
        if (x.contains("progress")) return s.warn;
        return fallback;
    }

    private XSSFCellStyle severityStyle(S s, String v, XSSFCellStyle fallback) {
        if (v == null) return fallback;
        String x = v.trim().toLowerCase();
        if (x.equals("critical") || x.equals("high")) return s.bad;
        if (x.equals("medium")) return s.warn;
        if (x.equals("low") || x.equals("minor")) return s.neutral;
        return fallback;
    }

    private XSSFCellStyle bugStatusStyle(S s, String v, XSSFCellStyle fallback) {
        if (v == null) return fallback;
        String x = v.trim().toUpperCase();
        if (x.equals("RESOLVED") || x.equals("CLOSED") || x.equals("VERIFIED")) return s.good;
        if (x.equals("INVALID_BUG") || x.equals("REJECTED") || x.equals("INVALID")) return s.neutral;
        return s.bad;
    }

    // ── Low-level cell helpers ─────────────────────────────────────────────────
    private static void cell(Row row, int col, String value, XSSFCellStyle style) {
        Cell c = row.createCell(col);
        c.setCellValue(value == null ? "" : value);
        c.setCellStyle(style);
    }

    private static void numCell(Row row, int col, Double value, XSSFCellStyle style) {
        Cell c = row.createCell(col);
        if (value != null) c.setCellValue(value);
        else c.setCellValue("");
        c.setCellStyle(style);
    }

    private static void autosize(XSSFSheet sheet, int cols) {
        for (int i = 0; i < cols; i++) {
            try {
                sheet.autoSizeColumn(i);
                int w = sheet.getColumnWidth(i);
                if (w < 2600) sheet.setColumnWidth(i, 2600);
                if (w > 16000) sheet.setColumnWidth(i, 16000);
            } catch (Exception e) {
                sheet.setColumnWidth(i, 4200);
            }
        }
    }

    // ── Value coercion from the JSON map ───────────────────────────────────────
    @SuppressWarnings("unchecked")
    private static Map<String, Object> asMap(Object o) {
        return (o instanceof Map) ? (Map<String, Object>) o : new HashMap<>();
    }

    @SuppressWarnings("unchecked")
    private static List<Map<String, Object>> asList(Object o) {
        if (o instanceof List) {
            List<Map<String, Object>> out = new ArrayList<>();
            for (Object item : (List<Object>) o) if (item instanceof Map) out.add((Map<String, Object>) item);
            return out;
        }
        return new ArrayList<>();
    }

    private static String str(Map<String, Object> m, String k) {
        Object v = m.get(k);
        return v == null ? "" : String.valueOf(v);
    }

    private static String dateStr(Map<String, Object> m, String k) {
        String v = str(m, k);
        if (v.isEmpty() || v.equals("\u2014")) return "";
        if (v.length() >= 10 && v.charAt(4) == '-' && v.charAt(7) == '-') return v.substring(0, 10);
        return v;
    }

    private static boolean bool(Map<String, Object> m, String k) {
        Object v = m.get(k);
        if (v instanceof Boolean) return (Boolean) v;
        return "true".equalsIgnoreCase(String.valueOf(v)) || "yes".equalsIgnoreCase(String.valueOf(v));
    }

    private static Double dbl(Map<String, Object> m, String k) {
        Object v = m.get(k);
        if (v instanceof Number) return ((Number) v).doubleValue();
        String sv = String.valueOf(v);
        if (v == null || sv.isEmpty() || sv.equals("null") || sv.equals("\u2014")) return null;
        try { return Double.parseDouble(sv); } catch (Exception e) { return null; }
    }

    private static int intOf(Map<String, Object> m, String k) {
        Double d = dbl(m, k);
        return d == null ? 0 : (int) Math.round(d);
    }

    private static String orDash(String v) {
        return (v == null || v.isEmpty()) ? "\u2014" : v;
    }

    private static String round1(double d) {
        return String.valueOf(Math.round(d * 10.0) / 10.0);
    }

    private static String humanize(String status) {
        if (status == null || status.isEmpty()) return "";
        String[] parts = status.replace('_', ' ').trim().toLowerCase().split(" ");
        StringBuilder sb = new StringBuilder();
        for (String p : parts) {
            if (p.isEmpty()) continue;
            sb.append(Character.toUpperCase(p.charAt(0))).append(p.substring(1)).append(' ');
        }
        return sb.toString().trim();
    }

    private static String checksum(List<Map<String, Object>> crs) {
        try {
            StringBuilder sb = new StringBuilder();
            for (Map<String, Object> cr : crs) sb.append(str(cr, "crNumber")).append('|').append(str(cr, "status")).append(';');
            MessageDigest md = MessageDigest.getInstance("SHA-256");
            byte[] digest = md.digest(sb.toString().getBytes(java.nio.charset.StandardCharsets.UTF_8));
            StringBuilder hex = new StringBuilder();
            for (byte b : digest) hex.append(String.format("%02x", b));
            return hex.toString();
        } catch (Exception e) {
            return "n/a";
        }
    }

    // ── Style bundle ────────────────────────────────────────────────────────────
    private static class S {
        final XSSFCellStyle title, subtitle, header, body, bodyZebra, num, numZebra,
                good, warn, bad, neutral, info, link, sumLabel, sumValue, footer;

        S(XSSFWorkbook wb) {
            XSSFColor brandDark = c(30, 41, 59);
            XSSFColor indigo = c(79, 70, 229);
            XSSFColor indigoLight = c(224, 231, 255);
            XSSFColor zebra = c(244, 246, 251);
            XSSFColor bodyText = c(51, 65, 85);
            XSSFColor gridCol = c(203, 213, 225);
            XSSFColor white = c(255, 255, 255);
            XSSFColor headerSub = c(165, 180, 252);
            XSSFColor footerGrey = c(148, 163, 184);

            title = wb.createCellStyle();
            title.setFillForegroundColor(brandDark);
            title.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            title.setAlignment(HorizontalAlignment.LEFT);
            title.setVerticalAlignment(VerticalAlignment.CENTER);
            title.setFont(font(wb, 15, true, white));

            subtitle = wb.createCellStyle();
            subtitle.setFillForegroundColor(indigo);
            subtitle.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            subtitle.setVerticalAlignment(VerticalAlignment.CENTER);
            subtitle.setFont(font(wb, 11, true, white));

            header = wb.createCellStyle();
            header.setFillForegroundColor(brandDark);
            header.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            header.setAlignment(HorizontalAlignment.LEFT);
            header.setVerticalAlignment(VerticalAlignment.CENTER);
            header.setWrapText(true);
            header.setFont(font(wb, 10, true, headerSub));
            border(header, gridCol);

            body = wb.createCellStyle();
            body.setVerticalAlignment(VerticalAlignment.TOP);
            body.setFont(font(wb, 10, false, bodyText));
            border(body, gridCol);

            bodyZebra = wb.createCellStyle();
            bodyZebra.cloneStyleFrom(body);
            bodyZebra.setFillForegroundColor(zebra);
            bodyZebra.setFillPattern(FillPatternType.SOLID_FOREGROUND);

            num = wb.createCellStyle();
            num.cloneStyleFrom(body);
            num.setAlignment(HorizontalAlignment.CENTER);

            numZebra = wb.createCellStyle();
            numZebra.cloneStyleFrom(bodyZebra);
            numZebra.setAlignment(HorizontalAlignment.CENTER);

            good = badge(wb, c(209, 250, 229), c(6, 95, 70), gridCol);
            warn = badge(wb, c(254, 243, 199), c(146, 64, 14), gridCol);
            bad = badge(wb, c(254, 226, 226), c(153, 27, 27), gridCol);
            neutral = badge(wb, c(241, 245, 249), c(71, 85, 105), gridCol);
            info = badge(wb, indigoLight, c(55, 48, 163), gridCol);

            link = wb.createCellStyle();
            link.setVerticalAlignment(VerticalAlignment.TOP);
            XSSFFont lf = font(wb, 10, true, c(37, 99, 235));
            lf.setUnderline(Font.U_SINGLE);
            link.setFont(lf);
            border(link, gridCol);

            sumLabel = wb.createCellStyle();
            sumLabel.setFont(font(wb, 11, true, bodyText));
            sumLabel.setVerticalAlignment(VerticalAlignment.CENTER);

            sumValue = wb.createCellStyle();
            sumValue.setFont(font(wb, 11, false, c(15, 23, 42)));
            sumValue.setVerticalAlignment(VerticalAlignment.CENTER);

            footer = wb.createCellStyle();
            footer.setFillForegroundColor(c(15, 23, 42));
            footer.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            footer.setAlignment(HorizontalAlignment.CENTER);
            footer.setVerticalAlignment(VerticalAlignment.CENTER);
            footer.setFont(font(wb, 9, true, footerGrey));
        }

        private static XSSFCellStyle badge(XSSFWorkbook wb, XSSFColor bg, XSSFColor fg, XSSFColor gridCol) {
            XSSFCellStyle st = wb.createCellStyle();
            st.setFillForegroundColor(bg);
            st.setFillPattern(FillPatternType.SOLID_FOREGROUND);
            st.setAlignment(HorizontalAlignment.CENTER);
            st.setVerticalAlignment(VerticalAlignment.CENTER);
            st.setFont(font(wb, 10, true, fg));
            border(st, gridCol);
            return st;
        }

        private static XSSFFont font(XSSFWorkbook wb, int size, boolean bold, XSSFColor color) {
            XSSFFont f = wb.createFont();
            f.setFontName("Segoe UI");
            f.setFontHeightInPoints((short) size);
            f.setBold(bold);
            f.setColor(color);
            return f;
        }

        private static void border(XSSFCellStyle st, XSSFColor color) {
            st.setBorderTop(BorderStyle.THIN);
            st.setTopBorderColor(color);
            st.setBorderBottom(BorderStyle.THIN);
            st.setBottomBorderColor(color);
            st.setBorderLeft(BorderStyle.THIN);
            st.setLeftBorderColor(color);
            st.setBorderRight(BorderStyle.THIN);
            st.setRightBorderColor(color);
        }

        private static XSSFColor c(int r, int g, int b) {
            return new XSSFColor(new byte[]{(byte) r, (byte) g, (byte) b}, null);
        }
    }
}
